#!/usr/bin/env python3
"""
Packs the country flags in assets/Flags into the atlas embedded in the channel.

Each `<code>.png` (ISO 3166-1 alpha-2, any size, 4:3) is resized to FLAG_W x FLAG_H and placed in
one image, `data/flags` (a PNG without an extension, like the other files in data/). The order of
the flags in the atlas is written to source/ghosts/flags_generated.h, which the leaderboard uses to
find a country's flag.

The flags come from flag-icons (MIT, https://github.com/lipis/flag-icons), rendered from its 4:3
SVGs; see assets/THIRD_PARTY_NOTICES.txt.

Requires Pillow: pip install pillow
Usage (from the repository root): python tools/make_flags.py
"""

import pathlib

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE_DIR = ROOT / "assets" / "Flags"
ATLAS = ROOT / "data" / "flags"
HEADER = ROOT / "source" / "ghosts" / "flags_generated.h"

FLAG_W, FLAG_H = 20, 15
COLS = 16

flags = sorted(SOURCE_DIR.glob("*.png"), key=lambda p: p.stem.upper())
codes = [p.stem.upper() for p in flags]
for code in codes:
    if len(code) != 2 or not code.isalpha():
        raise SystemExit(f"{code}: flag files must be named after a two-letter country code")

rows = (len(flags) + COLS - 1) // COLS
atlas = Image.new("RGBA", (COLS * FLAG_W, rows * FLAG_H), (0, 0, 0, 0))
for i, path in enumerate(flags):
    flag = Image.open(path).convert("RGBA").resize((FLAG_W, FLAG_H), Image.LANCZOS)
    atlas.paste(flag, ((i % COLS) * FLAG_W, (i // COLS) * FLAG_H))
atlas.save(ATLAS, format="PNG", optimize=True)

with open(HEADER, "w", newline="\r\n") as h:
    h.write("/* Generated by tools/make_flags.py from assets/Flags. Do not edit. */\n\n")
    h.write("#ifndef RRC_FLAGS_GENERATED_H\n#define RRC_FLAGS_GENERATED_H\n\n")
    h.write(f"#define RRC_FLAG_W {FLAG_W}\n#define RRC_FLAG_H {FLAG_H}\n#define RRC_FLAG_ATLAS_COLS {COLS}\n")
    h.write(f"#define RRC_FLAG_COUNT {len(codes)}\n\n")
    h.write("/* Country codes of the flags in the atlas, two letters each, in atlas order (sorted). */\n")
    h.write("static const char rrc_flag_codes[] =\n")
    for i in range(0, len(codes), 20):
        h.write('    "' + "".join(codes[i:i + 20]) + '"\n')
    h.write("    ;\n\n#endif\n")

print(f"{len(codes)} flags -> {ATLAS.relative_to(ROOT)} ({ATLAS.stat().st_size} bytes), {HEADER.relative_to(ROOT)}")
